// Mock-дані для секції напрямків на Головній і сторінки «Здивуй мене».
// На Етапі 2 вони переїдуть у таблицю destinations у Supabase.

export type DestinationTone = 'primary' | 'warm' | 'success' | 'sky'

export type Destination = {
  id: string
  city: string
  country?: string
  priceFrom: number
  stops: number
  duration: string
  photo: string
  tone: DestinationTone
  hotel: string
  // Місяці, коли туди найкраще їхати: 1 = січень … 12 = грудень
  bestMonths: number[]
  // Коли й як краще їхати — для сторінки «Здивуй мене»
  description: string
}

export const budgets = [800, 1500, 2500] as const

export const destinations: Destination[] = [
  {
    id: 'vancouver',
    city: 'Vancouver',
    country: 'Canada',
    priceFrom: 520,
    stops: 0,
    duration: '2h 25m',
    photo: 'Vancouver harbour and mountains',
    tone: 'success',
    hotel: 'Fairmont Waterfront',
    bestMonths: [6, 7, 8, 9],
    description:
      'Summer is dry and mild — perfect for Stanley Park, kayaking and day trips to Whistler. Stay by the waterfront and get around by SkyTrain and SeaBus.',
  },
  {
    id: 'new-york',
    city: 'New York',
    country: 'United States',
    priceFrom: 560,
    stops: 0,
    duration: '5h 40m',
    photo: 'Manhattan skyline',
    tone: 'primary',
    hotel: 'The Standard High Line',
    bestMonths: [4, 5, 6, 9, 10],
    description:
      'Spring and early autumn bring comfortable walking weather and fewer crowds than summer. Stay in Manhattan or Brooklyn and use the subway.',
  },
  {
    id: 'chicago',
    city: 'Chicago',
    country: 'United States',
    priceFrom: 430,
    stops: 0,
    duration: '4h 20m',
    photo: 'Chicago river architecture',
    tone: 'sky',
    hotel: 'Hotel Chicago Riverwalk',
    bestMonths: [5, 6, 7, 8, 9],
    description:
      'Late spring to early autumn is festival season by the lake. Start with the river architecture cruise, then explore neighbourhoods on the L train.',
  },
  {
    id: 'honolulu',
    city: 'Honolulu',
    country: 'United States',
    priceFrom: 640,
    stops: 0,
    duration: '5h 35m',
    photo: 'Waikiki beach',
    tone: 'sky',
    hotel: 'Moana Surfrider',
    bestMonths: [4, 5, 6, 9, 10],
    description:
      'April–June and September–October have the best mix of sunshine, calm seas and lower prices. Rent a car for a day to circle the North Shore.',
  },
  {
    id: 'cancun',
    city: 'Cancún',
    country: 'Mexico',
    priceFrom: 690,
    stops: 0,
    duration: '5h 15m',
    photo: 'Turquoise beach in Cancún',
    tone: 'sky',
    hotel: 'Hotel Riu Caribe',
    bestMonths: [12, 1, 2, 3, 4],
    description:
      'December to April is the dry season with calm turquoise water. Base yourself in the Hotel Zone and take the ADO bus to Tulum and the cenotes.',
  },
  {
    id: 'montreal',
    city: 'Montréal',
    country: 'Canada',
    priceFrom: 610,
    stops: 1,
    duration: '8h 10m',
    photo: 'Old Montréal street',
    tone: 'warm',
    hotel: 'Hôtel Nelligan',
    bestMonths: [6, 7, 8, 9, 12],
    description:
      'Summer is all jazz and food festivals; December turns the old town into a snowy postcard. The metro covers everything.',
  },
  {
    id: 'san-jose',
    city: 'San José',
    country: 'Costa Rica',
    priceFrom: 740,
    stops: 1,
    duration: '8h 45m',
    photo: 'Rainforest canopy',
    tone: 'success',
    hotel: 'Hotel Grano de Oro',
    bestMonths: [12, 1, 2, 3, 4],
    description:
      'The dry season from December to April is best for volcano hikes and beaches. Rent a 4×4 — many of the best spots are off paved roads.',
  },
  {
    id: 'mexico-city',
    city: 'Mexico City',
    priceFrom: 780,
    stops: 0,
    duration: '4h 25m',
    photo: 'Mexico City plaza',
    tone: 'sky',
    hotel: 'Hotel Carlota',
    bestMonths: [3, 4, 5, 10, 11],
    description:
      'Spring is warm and dry, and early November brings Día de Muertos. Stay in Roma or Condesa and use the metro or a taxi app between neighbourhoods.',
  },
  {
    id: 'london',
    city: 'London',
    country: 'United Kingdom',
    priceFrom: 1050,
    stops: 0,
    duration: '10h 35m',
    photo: 'Thames at dusk',
    tone: 'primary',
    hotel: 'The Hoxton Holborn',
    bestMonths: [5, 6, 7, 8, 9],
    description:
      'Late spring and summer have long light evenings for parks and markets. Tap your bank card on the Tube — fares are capped daily.',
  },
  {
    id: 'lisbon',
    city: 'Lisbon',
    country: 'Portugal',
    priceFrom: 1090,
    stops: 1,
    duration: '15h 05m',
    photo: 'Lisbon rooftops',
    tone: 'warm',
    hotel: 'Memmo Alfama',
    bestMonths: [4, 5, 6, 9, 10],
    description:
      'Spring and early autumn are sunny without the summer heat and crowds. Ride tram 28 early in the morning and take a day trip to Sintra.',
  },
  {
    id: 'amsterdam',
    city: 'Amsterdam',
    country: 'Netherlands',
    priceFrom: 1120,
    stops: 0,
    duration: '10h 40m',
    photo: 'Amsterdam canals',
    tone: 'sky',
    hotel: 'Pulitzer Amsterdam',
    bestMonths: [4, 5, 9],
    description:
      'Mid-April to May is tulip season; September is quieter and still mild. Rent a bike for a day — it is the fastest way across the city.',
  },
  {
    id: 'paris',
    city: 'Paris',
    country: 'France',
    priceFrom: 1150,
    stops: 0,
    duration: '10h 50m',
    photo: 'Paris rooftops at sunset',
    tone: 'warm',
    hotel: 'Hôtel des Grands Boulevards',
    bestMonths: [4, 5, 6, 9, 10],
    description:
      'April–June and September–October give soft light, terraces and shorter queues. Book museum time slots in advance and walk along the river.',
  },
  {
    id: 'barcelona',
    city: 'Barcelona',
    country: 'Spain',
    priceFrom: 1180,
    stops: 1,
    duration: '13h 30m',
    photo: 'Barcelona Gothic Quarter',
    tone: 'warm',
    hotel: 'Hotel Casa Fuster',
    bestMonths: [5, 6, 9, 10],
    description:
      'Late spring and early autumn are warm enough for the beach without August crowds. Book Sagrada Família ahead and use a metro travel card.',
  },
  {
    id: 'tokyo',
    city: 'Tokyo',
    country: 'Japan',
    priceFrom: 1240,
    stops: 0,
    duration: '11h 20m',
    photo: 'Tokyo street at dusk',
    tone: 'primary',
    hotel: 'Hotel Shinjuku',
    bestMonths: [3, 4, 10, 11],
    description:
      'Late March to early April is cherry-blossom season; October–November brings clear skies and autumn colours. Get a Suica card for trains and shops.',
  },
  {
    id: 'rome',
    city: 'Rome',
    country: 'Italy',
    priceFrom: 1260,
    stops: 1,
    duration: '14h 50m',
    photo: 'Roman Forum at golden hour',
    tone: 'warm',
    hotel: 'Hotel Artemide',
    bestMonths: [4, 5, 6, 9, 10],
    description:
      'Spring and autumn are ideal for walking between ruins without midsummer heat. Book the Colosseum and Vatican online and stay near Monti or Trastevere.',
  },
  {
    id: 'seoul',
    city: 'Seoul',
    country: 'South Korea',
    priceFrom: 1310,
    stops: 0,
    duration: '12h 45m',
    photo: 'Seoul at night',
    tone: 'primary',
    hotel: 'RYSE Autograph Collection',
    bestMonths: [4, 5, 9, 10, 11],
    description:
      'Spring blossoms and crisp autumn foliage are the highlights. The metro is excellent — load a T-money card and try the night markets.',
  },
  {
    id: 'athens',
    city: 'Athens',
    country: 'Greece',
    priceFrom: 1350,
    stops: 1,
    duration: '16h 20m',
    photo: 'Acropolis view',
    tone: 'sky',
    hotel: 'Electra Metropolis',
    bestMonths: [5, 6, 9, 10],
    description:
      'May–June and September–October are warm with calm seas for island hopping. Visit the Acropolis right at opening, then catch a ferry from Piraeus.',
  },
  {
    id: 'reykjavik',
    city: 'Reykjavík',
    country: 'Iceland',
    priceFrom: 1380,
    stops: 1,
    duration: '12h 40m',
    photo: 'Reykjavík harbour',
    tone: 'success',
    hotel: 'Center Hotels Plaza',
    bestMonths: [2, 3, 6, 7, 8],
    description:
      'June–August brings the midnight sun and open highland roads; February–March is best for the northern lights. A rental car makes the Golden Circle easy.',
  },
  {
    id: 'bangkok',
    city: 'Bangkok',
    country: 'Thailand',
    priceFrom: 1420,
    stops: 1,
    duration: '19h 10m',
    photo: 'Bangkok temple',
    tone: 'warm',
    hotel: 'The Siam',
    bestMonths: [11, 12, 1, 2],
    description:
      'November to February is the cool, dry season. Use river boats and the Skytrain to avoid traffic, and add a few days on the islands.',
  },
  {
    id: 'buenos-aires',
    city: 'Buenos Aires',
    country: 'Argentina',
    priceFrom: 1460,
    stops: 1,
    duration: '15h 40m',
    photo: 'Colourful La Boca street',
    tone: 'warm',
    hotel: 'Palacio Duhau',
    bestMonths: [3, 4, 5, 9, 10, 11],
    description:
      'Southern spring and autumn are mild and great for walking. Stay in Palermo or Recoleta and plan dinners late — restaurants fill up after 9 pm.',
  },
  {
    id: 'marrakech',
    city: 'Marrakech',
    country: 'Morocco',
    priceFrom: 1560,
    stops: 1,
    duration: '17h 55m',
    photo: 'Marrakech spice market',
    tone: 'warm',
    hotel: 'Riad Kniza',
    bestMonths: [3, 4, 5, 10, 11],
    description:
      'Spring and autumn avoid the extreme summer heat. Stay in a riad inside the medina and add a night in the Atlas mountains or the desert.',
  },
  {
    id: 'hanoi',
    city: 'Hanoi',
    country: 'Vietnam',
    priceFrom: 1590,
    stops: 1,
    duration: '18h 30m',
    photo: 'Hanoi Old Quarter',
    tone: 'success',
    hotel: "Hotel de l'Opera Hanoi",
    bestMonths: [3, 4, 10, 11],
    description:
      'Spring and autumn are mild and dry. Explore the Old Quarter on foot and book an overnight cruise in Ha Long Bay.',
  },
  {
    id: 'dubai',
    city: 'Dubai',
    country: 'United Arab Emirates',
    priceFrom: 1640,
    stops: 0,
    duration: '15h 50m',
    photo: 'Dubai skyline',
    tone: 'sky',
    hotel: 'Address Downtown',
    bestMonths: [11, 12, 1, 2, 3],
    description:
      'November to March is warm and sunny rather than scorching. The metro links the main sights; book an evening desert tour for the dunes.',
  },
  {
    id: 'singapore',
    city: 'Singapore',
    priceFrom: 1720,
    stops: 0,
    duration: '16h 40m',
    photo: 'Gardens by the Bay',
    tone: 'success',
    hotel: 'Parkroyal Collection Pickering',
    bestMonths: [2, 3, 4],
    description:
      'February to April is drier between monsoons. Hawker centres are the best-value food in the city, and the MRT goes everywhere.',
  },
  {
    id: 'rio',
    city: 'Rio de Janeiro',
    country: 'Brazil',
    priceFrom: 1780,
    stops: 1,
    duration: '16h 05m',
    photo: 'Sugarloaf Mountain',
    tone: 'sky',
    hotel: 'Fasano Rio de Janeiro',
    bestMonths: [12, 1, 2, 3],
    description:
      'December to March is summer and carnival season. Stay in Ipanema or Leblon and use official taxis or a ride app at night.',
  },
  {
    id: 'sydney',
    city: 'Sydney',
    country: 'Australia',
    priceFrom: 1890,
    stops: 0,
    duration: '15h 05m',
    photo: 'Sydney Opera House',
    tone: 'sky',
    hotel: 'Ovolo Woolloomooloo',
    bestMonths: [3, 4, 5, 9, 10, 11],
    description:
      'Southern spring and autumn are warm without peak summer prices. Take the ferry to Manly and walk the Bondi to Coogee coastal path.',
  },
  {
    id: 'bali',
    city: 'Bali',
    country: 'Indonesia',
    priceFrom: 1980,
    stops: 1,
    duration: '20h 30m',
    photo: 'Rice terraces in Bali',
    tone: 'success',
    hotel: 'COMO Uma Ubud',
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
    description:
      'April to October is the dry season. Split your stay between Ubud for rice terraces and the coast for beaches, and hire a driver for day trips.',
  },
  {
    id: 'cape-town',
    city: 'Cape Town',
    country: 'South Africa',
    priceFrom: 2150,
    stops: 1,
    duration: '22h 40m',
    photo: 'Table Mountain',
    tone: 'success',
    hotel: 'The Silo Hotel',
    bestMonths: [11, 12, 1, 2, 3],
    description:
      'Southern summer is warm and great for beaches and wine country. Hike or take the cable car up Table Mountain on a clear morning.',
  },
  {
    id: 'queenstown',
    city: 'Queenstown',
    country: 'New Zealand',
    priceFrom: 2290,
    stops: 1,
    duration: '17h 20m',
    photo: 'Lake Wakatipu',
    tone: 'primary',
    hotel: "Eichardt's Private Hotel",
    bestMonths: [12, 1, 2, 3, 6, 7, 8],
    description:
      'Summer is for hiking and lake days; June–August is ski season. Rent a car and drive to Milford Sound for a day.',
  },
  {
    id: 'male',
    city: 'Malé',
    country: 'Maldives',
    priceFrom: 2420,
    stops: 1,
    duration: '24h 10m',
    photo: 'Overwater villas',
    tone: 'sky',
    hotel: 'Kurumba Maldives',
    bestMonths: [11, 12, 1, 2, 3, 4],
    description:
      'November to April is the dry season with calm, clear water for snorkelling. Choose a resort with the seaplane or speedboat transfer included.',
  },
]

export const surprise = {
  moreTrips: 42,
}
